# Generated by Django 6.0.5 on 2026-07-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.CharField(choices=[('task_not_created', 'Task Not Created'), ('task_not_saved', 'Task Not Saved'), ('task_not_completed', 'Task Not Completed'), ('task_not_edited', 'Task Not Edited'), ('task_not_deleted', 'Task Not Deleted'), ('other', 'Other')], max_length=50)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=500),
        ),
    ]
