# Generated by Django 6.0.6 on 2026-08-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_remove_task_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='issue',
            field=models.CharField(choices=[('task_not_created', 'Task Not Created'), ('task_not_saved', 'Task Not Saved'), ('task_not_completed', 'Task Not Completed'), ('task_not_edited', 'Task Not Edited'), ('task_not_deleted', 'Task Not Deleted'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20),
        ),
    ]
