# Generated by Django 6.0.6 on 2026-08-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_contact_issue_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='issue',
            field=models.CharField(choices=[('task_not_created', 'Task Not Created'), ('task_not_saved', 'Task Not Saved'), ('task_not_completed', 'Task Not Completed'), ('task_not_edited', 'Task Not Edited'), ('task_not_deleted', 'Task Not Deleted'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=20),
        ),
    ]
