# Generated by Django 6.0.6 on 2026-08-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_alter_contact_issue_alter_contact_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='priority',
        ),
    ]
